<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Content Remove="tests\**\*" />
    <EmbeddedResource Remove="tests\**\*" />
    <None Remove="tests\**\*" />
    <Compile Remove="tools\**\*.cs" />
    <Content Remove="tools\**\*" />
    <EmbeddedResource Remove="tools\**\*" />
    <None Remove="tools\**\*" />
    <Compile Remove="tmp\**\*.cs" />
    <Content Remove="tmp\**\*" />
    <EmbeddedResource Remove="tmp\**\*" />
    <None Remove="tmp\**\*" />
  </ItemGroup>

</Project>
