// <auto-generated />
using System;
using BitacoraEvidencias.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitacoraEvidencias.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cct")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Consecutivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curp")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EvidenciasCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolioCertificado")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOficio")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("NumeroOficio");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("Username");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.CasoCorreccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuditoriaEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditoriaUltimaObservacion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditoriaUltimaRevisionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditoriaUltimoResultado")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditoriaUltimoUsuario")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AuditoriaUltimoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuditorUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cct")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Consecutivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Curp")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenciaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelEducativo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("OficioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodoFin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodoInicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoCorreccion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Validador")
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuditoriaEstado");

                    b.HasIndex("AuditorUsuarioId");

                    b.HasIndex("Cct");

                    b.HasIndex("Curp");

                    b.HasIndex("Estatus");

                    b.HasIndex("Folio");

                    b.HasIndex("NivelEducativo");

                    b.HasIndex("OficioId", "Consecutivo")
                        .IsUnique();

                    b.HasIndex("OficioId", "NivelEducativo")
                        .IsUnique();

                    b.ToTable("CasosCorreccion", t =>
                        {
                            t.HasCheckConstraint("CK_CasosCorreccion_AuditoriaEstado", "\"AuditoriaEstado\" IN ('Pendiente', 'Coincidente', 'No coincidente')");

                            t.HasCheckConstraint("CK_CasosCorreccion_Estatus", "\"Estatus\" IN ('Pendiente', 'En proceso', 'Completado', 'Rechazado')");

                            t.HasCheckConstraint("CK_CasosCorreccion_NivelEducativo", "\"NivelEducativo\" IN ('Primaria', 'Secundaria')");
                        });
                });

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.EvidenciaFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CasoCorreccionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEvidencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaMiniatura")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEvidencia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CasoCorreccionId");

                    b.ToTable("EvidenciasFoto", t =>
                        {
                            t.HasCheckConstraint("CK_EvidenciasFoto_TipoEvidencia", "\"TipoEvidencia\" IN ('Oficio', 'Lista', 'Extra')");
                        });
                });

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.Oficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaOficio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOficio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroOficio")
                        .IsUnique();

                    b.ToTable("Oficios");
                });

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BloqueadoHastaUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoAccesoUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioNormalizado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioNormalizado")
                        .IsUnique();

                    b.HasIndex("Rol", "Activo");

                    b.ToTable("UsuariosSistema");
                });

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.CasoCorreccion", b =>
                {
                    b.HasOne("BitacoraEvidencias.Web.Models.UsuarioSistema", "AuditorUsuario")
                        .WithMany()
                        .HasForeignKey("AuditorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BitacoraEvidencias.Web.Models.Oficio", "Oficio")
                        .WithMany("Casos")
                        .HasForeignKey("OficioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditorUsuario");

                    b.Navigation("Oficio");
                });

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.EvidenciaFoto", b =>
                {
                    b.HasOne("BitacoraEvidencias.Web.Models.CasoCorreccion", "CasoCorreccion")
                        .WithMany("Evidencias")
                        .HasForeignKey("CasoCorreccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CasoCorreccion");
                });

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.CasoCorreccion", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("BitacoraEvidencias.Web.Models.Oficio", b =>
                {
                    b.Navigation("Casos");
                });
#pragma warning restore 612, 618
        }
    }
}






